<?php

namespace OAuth2ServerBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class OAuth2ServerBundle extends Bundle
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $this->container->get('biz');
        $biz['migration.directories'][] = __DIR__ . '/Migrations';
        $biz['autoload.aliases']['OAuth2ServerBundle'] = 'OAuth2ServerBundle\Biz';
    }

}
